name       : haskell-QuickCheck
version    : '2.14'
release    : 6
source     :
    - https://hackage.haskell.org/package/QuickCheck-2.14/QuickCheck-2.14.tar.gz : 52be1407fb19f5f3b5aa06d41fac745536d08306adaf6dde46a62255d16c384a
license    : BSD-3-Clause
component  : programming.haskell
summary    : QuickCheck is a library for random testing of program properties.
description: |
    QuickCheck is a library for random testing of program properties
builddeps  :
    - haskell-cabal-install
    - haskell-splitmix-devel
    - haskell-tf-random-devel
rundeps    :
    - devel:
        - haskell-splitmix-devel
        - haskell-tf-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
