name       : haskell-QuickCheck
version    : 2.9.1
release    : 3
source     :
    - http://hackage.haskell.org/package/QuickCheck-2.9.1/QuickCheck-2.9.1.tar.gz : f8769cbef895a67f9bd1ac554faa577e6c1fb41e271425880a759009e454d05f
license    : BSD-3-Clause
component  : programming.haskell
summary    : QuickCheck is a library for random testing of program properties.
description: |
    QuickCheck is a library for random testing of program properties
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-random
    - haskell-tf-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
