name       : haskell-QuickCheck
version    : 2.9.1
release    : 1
source     :
    - http://hackage.haskell.org/package/QuickCheck-2.9.1/QuickCheck-2.9.1.tar.gz : f8769cbef895a67f9bd1ac554faa577e6c1fb41e271425880a759009e454d05f
license    : BSD-3-Clause
component  : programming
summary    : QuickCheck is a library for random testing of program properties. 
description: |
    QuickCheck is a library for random testing of program properties. 
builddeps  :
    - ghc
    - haskell-random
    - haskell-tf-random
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 QuickCheck-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/QuickCheck-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/QuickCheck-$version/*.a

