name       : haskell-QuickCheck
version    : 2.11.3
release    : 5
source     :
    - https://hackage.haskell.org/package/QuickCheck-2.11.3/QuickCheck-2.11.3.tar.gz : 488c5652139da0bac8b3e7d76f11320ded298549e62db530938bfee9ca981876
license    : BSD-3-Clause
component  : programming.haskell
summary    : QuickCheck is a library for random testing of program properties.
description: |
    QuickCheck is a library for random testing of program properties
builddeps  :
    - haskell-cabal-install
    - haskell-random
    - haskell-tf-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
